/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6xCVqcV1TZG
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Input } from "@/app/ui/input"
import { Button } from "@/app/ui/button"
import Link from "next/link"


// Asegúrate de que el componente esté exportado correctamente
const Register = () => {
  return (
    <div className="flex items-center justify-center min-h-screen bg-gradient-to-r from-[#FFF5EE] to-[#FFEFD5]">
      <div className="w-full max-w-md p-8 bg-white rounded-lg shadow-xl">
        <h1 className="mb-2 text-2xl font-bold text-center">Registrarse</h1>
        <p className="mb-6 text-center text-muted-foreground">Crea una cuenta para acceder a tus cursos</p>
        <form className="space-y-4">
          <div>
            <label htmlFor="name" className="block text-sm font-medium">
              Usuario
            </label>
            <Input id="name" type="text" placeholder="Ingresa tu nombre" />
          </div>
          <div>
            <label htmlFor="email" className="block text-sm font-medium">
              Email
            </label>
            <Input id="email" type="email" placeholder="m@example.com" />
          </div>
          <div>
            <div className="flex items-center justify-between">
              <label htmlFor="password" className="block text-sm font-medium">
                Contraseña
              </label>
            </div>
            <Input id="password" type="password" placeholder="********" />
          </div>
          <Button className="w-full" variant="default">
            Registrarse
          </Button>
          <Button className="w-full" variant="outline">
            Registrarse con Google
          </Button>
        </form>
        <p className="mt-4 text-sm text-center text-muted-foreground">
          ¿Ya tienes una cuenta?{" "}
          <Link href="/login" className="text-blue-500" prefetch={false}>
            Iniciar sesión
          </Link>
        </p>
        <p className="mt-4 text-sm text-center text-muted-foreground">
          {" "}
          <Link href="/" className="text-blue-500" prefetch={false}>
            Volver al inicio
          </Link>
        </p>
      </div>
    </div>
  )
}

// Exporta el componente como exportación por defecto
export default Register;